project_name: ooni-sync
builds:
  - main: ooni-sync.go
    binary: ooni-sync
    goos:
      - windows
      - freebsd
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
      - arm
